### ISSUE TITLE
Без интервали в имената на файловете

### ISSUE THREAD

**Issue by nakov** [SoftUni/Programming-Basics-Book-Java-BG#1]
Да се направят огледални корекции за намерен проблем в C# книгата:
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/issues/232

- В имената на ресурсите не трябва да има интервали.
- Ресурсите да се именуват консистентно (както останалите във всчки глави).
- Ресурсите към Wiki страниците не тярбва да са в папката `\assets`.

**Comment by VKachanov** [comment]
Ресурсите (images) на Глава 4 са в папка `\assets`, няма интервали в имената им, за всеки случай съм добавил по едно -Java към всяко от имената (с изключение на картинките за GUI приложението), картинките за C# са изтрити (с изключение на тези за GUI приложението).

**Comment by nakov** [comment]
Тази задача приключена ли е? @udarensamolet ?

**Comment by udarensamolet** [comment]
@nakov Чаках да приключат редакторите, за да започна да работя по тях.

**Comment by udarensamolet** [comment]
done
