### ISSUE TITLE
По-добро форматиране на кода

### ISSUE THREAD

**Issue by nakov** [SoftUni/Programming-Basics-Book-Java-BG#14]
![image](https://user-images.githubusercontent.com/1689586/29517006-a6686aaa-867b-11e7-9a23-f58adf8cbd39.png)

Може да се направи global find & replace: `){` --> `) {`

**Comment by vncpetrov** [comment]
[c39b2761a9ebc6fe9151089c9d7d55f9b2d2f33e](https://github.com/SoftUni/Programming-Basics-Book-Java-BG/commit/c39b2761a9ebc6fe9151089c9d7d55f9b2d2f33e)
