### ISSUE TITLE
Изпуснат препинателен знак точка

### ISSUE THREAD

**Issue by Tuscann** [SoftUni/Programming-Basics-Book-Java-BG#15]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-Java-BG/blob/master/chapter-02-simple-calculations.md
## Описание
Напишете Java програма, който прочита от конзолата име, фамилия, възраст и град и печата съобщение от следния вид: You are <firstName> <lastName>, a <age>-years old person from <town>.
## Текущ текст
Има сложена точка но според мен тя е за края на изречението в книгата.
**Не е сложена точка в маркирания с друг цвят формат желан като изход.**

**Comment by vncpetrov** [comment]
Оправено е. [https://github.com/SoftUni/Programming-Basics-Book-Java-BG/commit/a96105500d86e294cd1eaff0002b336ea2a30925](https://github.com/SoftUni/Programming-Basics-Book-Java-BG/commit/a96105500d86e294cd1eaff0002b336ea2a30925)
