### ISSUE TITLE
Вдигане на шрифтовете в картинките от глава 5 (цикли)

### ISSUE THREAD

**Issue by nakov** [SoftUni/Programming-Basics-Book-Java-BG#16]
В глава 5 (цикли) картинките са екстремно дребни. Шрифтът е с размер не повече от 6-7pt, а трябва да е 12-14pt. Почти screenshots от тази глава (https://github.com/SoftUni/Programming-Basics-Book-Java-BG/blob/master/assets/chapter-1-images) трябва да се вземат наново:

07.Numbers-sum-39.png -> това е ОК, шрифтът е с нормален размер

Повечето картинки, обаче са екстремално дребни. Трябва ми микроскоп, за да ги видя. Ето примери:
02.Expression-01.png - шрифтовете са екстремално дребни
07.Numbers-sum-31.png - шрифтовете са екстремално дребни
...
Има още 50-60 картинки в тази глава с изключително дребен шрифт.

**Comment by vncpetrov** [comment]
Това май не е за 5-та глава? Там няма такива картинки. Да не става въпрос за 1-ва?

**Comment by nakov** [comment]
Да, първата глава. Сори, нещо съм се объркал.

**Comment by vncpetrov** [comment]
За преглед.

**Comment by nakov** [comment]
Поправих всички картинки, които имаха нужда.
