### ISSUE TITLE
Да се преведе английският текст за Turtle Graphics

### ISSUE THREAD

**Issue by nakov** [SoftUni/Programming-Basics-Book-Java-BG#17]
Моля преведете на български език това API описание в Turtle Graphics секцията на глава 5.1 (цикли). Не върви цялата книга да е на български е една страница да е зицяло на английски.

Ето линк: https://github.com/SoftUni/Programming-Basics-Book-Java-BG/blob/master/chapter-05-loops.md#Основни-методи-на-класа-turtle

**Comment by vncpetrov** [comment]
Fixed. [https://github.com/SoftUni/Programming-Basics-Book-Java-BG/commit/f983375fa5d8522836bf168f4b1e4eebe1149768](https://github.com/SoftUni/Programming-Basics-Book-Java-BG/commit/f983375fa5d8522836bf168f4b1e4eebe1149768)
