### ISSUE TITLE
Глава 3.1. - неработещ код в Пример: отлична оценка

### ISSUE THREAD

**Issue by AngelKalinkov** [SoftUni/Programming-Basics-Book-Java-BG#18]
## Текущ текст: https://github.com/SoftUni/Programming-Basics-Book-Java-BG/blob/master/assets/chapter-3-1-images/01.%D0%95xcellent-result-01.png
https://github.com/SoftUni/Programming-Basics-Book-Java-BG/blob/master/assets/chapter-3-1-images/02.Excellent-or-not-01.png

## Текст след поправката: double evaluation = Double.parseDouble(scanner.nextLine());

**Comment by vncpetrov** [comment]
При мен работи и с дробни числа.

**Comment by AngelKalinkov** [comment]
А при мен не се получава!? Може би повредата е някъде в моя телевизор :) Някакви предположения?

![capture](https://user-images.githubusercontent.com/31779913/30292852-4961b368-9740-11e7-8162-29fc870a1b4f.JPG)

**Comment by udarensamolet** [comment]
Scanner-a e вързан за System locale настройките и ако от там е избрана държава, в която `,` e десетичния знак, ще хвърля грешката, която получаваш.
Опциите са или да смениш настройките, или в самия код да добавиш например
`Scanner scanner = new Scanner(System.in).useLocale(Locale.US);`.

**Comment by AngelKalinkov** [comment]
Благодаря за информацията! Изобщо не се светнах, че това е проблемът, защото в Intellij като натиснеш точка се отпечатва точка, за разлика от Excel например, където излиза запетая. Благодаря още веднъж за съдействието!
