### ISSUE TITLE
Пропусната точка

### ISSUE THREAD

**Issue by Tuscann** [SoftUni/Programming-Basics-Book-Java-BG#19]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-Java-BG/blob/master/chapter-10-methods.md
## Описание

    Вземаме остатъка от числото, разделено на основата
    Добавяме остатъка от числото към предната част на низа, представящ резултата.
    Разделяме числото на основата.
    Повтаряме алгоритъма, докато входното число не стане 0.

## Текущ текст
 Вземаме остатъка от числото, разделено на основата
## Текст след поправката
 Вземаме остатъка от числото, разделено на основата.

**Comment by udarensamolet** [comment]
Fixed with [41e23e3](https://github.com/SoftUni/Programming-Basics-Book-Java-BG/commit/41e23e3ab093faaea031cfb16e6197257f99ef34).
