### ISSUE TITLE
Да се обнови списъка на авторите

### ISSUE THREAD

**Issue by nakov** [SoftUni/Programming-Basics-Book-Java-BG#2]
Да се обнови **списъка на авторите на Java книгата** спoред техния принос.
- Може да се ползват GitHub commit logs, за по-лесно ориентиране кой какъв принос има.
- Оригиналните автори от C# книгата се запазват и към тях се добавят Java авторите. Ако някой C# автор е писал нещо, което е излязло то употреба в Java книгата, може да се премахне.

**Comment by Teodor92** [comment]
1. Защо не разделим авторите на Original Аuthors и Java Book Authors? 
2. Не е ли удачно да сложим като Главни редактори @udarensamolet и @vncpetrov ? Все пак отделят доста повече време от нормалния автор, мисля че е хубаво да имат малко по-специално призвание :)

**Comment by nakov** [comment]
Съгласен. Нека направим секция "Programming Basics" автори и секция "Programming Basics - Java" автори.

За редакторите да. Ако намерим удобен начин как точно да стане в книгата.

**Comment by VKachanov** [comment]
В този ред на мисли - не трябва ли авторите на Java-книгата, които са намирали и повдигали issues в C#-книгата и които са добавяли/променяли текст, който в последствие се е използвал обратно в C#-книгата, да бъдат вписани като редактори в C#-книгата?

**Comment by nakov** [comment]
Аз съм съгласен, стига **да има значим принос** (да не са примерно 2 поправени думи в грешно изписано изречение). Ако има такива, сигнализирайте, за да ги добавим.

**Comment by VKachanov** [comment]
Съгласен съм - приноса трябва да е значим - точно затова предложих Java-авторите, чиито текст/идеи/намерени неща за поправяне са използвани обратно в C#-книгата, да бъдат считани за редактори на C#-книгата (нали това е част от редакторската работа). Иначе разделянето на original-автори и Java-автори би омаловажило донякъде работата на Java-авторите - вярно е, че не сме писали на празен бял лист хартия, но примерно в моята глава освен решенията на задачите и смяната на картинките от C# на Java се наложи да се добавят около 40 реда  текст, включително забравени описания на оператори, забравени решения на задачи и забравени картинки с решения.

**Comment by nakov** [comment]
ОК, ако имате конкретни предложения в стил "_предлагам да добавим Гошо за автор заради тези и тези приноси_", пишете и да действаме.

**Comment by nakov** [comment]
Авторите са разделени на две групи, както сме коментирали: Java автори (основни, с акцент върху тях), C# автори (признание и към техния принос).

![image](https://user-images.githubusercontent.com/1689586/50558956-d9fb6780-0cfa-11e9-9fc5-96ddee66e52d.png)
