### ISSUE TITLE
Глава 2.1. - несъответствие м/у код и изход в Пример: лице на правоъгълник в равнината.

### ISSUE THREAD

**Issue by AngelKalinkov** [SoftUni/Programming-Basics-Book-Java-BG#21]
## Текст след поправката: 
![image](https://user-images.githubusercontent.com/31779913/30516364-885fd028-9b45-11e7-9019-4765d2eee2af.png)

**Comment by udarensamolet** [comment]
Кодът работи коректно и дава резултат 100/100 в Judge системата.

**Comment by AngelKalinkov** [comment]
Никъде не съм казал, че проблемът е в кода, а само, че този код няма да доведе до показания в примера изход. Ако напишете код, с който да изкарате такъв изход, то Judge няма да го хареса и точно затова съм предложил не промяна в кода, а промяна в посочения изход.
