### ISSUE TITLE
Глава 2.1. - несъответствие м/у код и изход в Пример: лице на правоъгълник в равнината. Моля прочетете внимателно преди да маркирате отново с "invalid"!

### ISSUE THREAD

**Issue by AngelKalinkov** [SoftUni/Programming-Basics-Book-Java-BG#22]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-Java-BG/blob/master/chapter-02-simple-calculations.md

## Описание
В "Пример: лице на правоъгълник в равнината", кодът посочен за решаване на задачата, няма да доведе до посочения изход, който освен това се различава от заложения в Judge.

## Текущ текст
https://github.com/SoftUni/Programming-Basics-Book-Java-BG/blob/master/assets/chapter-2-1-images/04.Console-output-06.png

## Текст след поправката 
![30516364-885fd028-9b45-11e7-9019-4765d2eee2af](https://user-images.githubusercontent.com/31779913/30709579-6e34149c-9f0b-11e7-8acc-f4ab0aa22ea1.png)

**Comment by udarensamolet** [comment]
Несъответствие между кода и изхода няма. Ако тестваме кода в Judge, дава резултат 100/100.

Ако проблема е в това, че в посочената картинка има десетичен знак и 0 след цялото число, а при теб в IntelliJ няма такива, то това не е проблем, кода работи коректно и Judge системата го приема.

Кода е тестван на две устройства, като на единия се виждат въпросните точка и 0, а на другия - не. И на двете кода работи коректо.

Моля за обратна връзка дали според теб това е проблема, тъй като аз не виждам нещо некоректно в самия код.

**Comment by AngelKalinkov** [comment]
Здравейте! Както първия път, така и сега никъде не казвам, че кодът е грешен. Но продължавам да твърдя, че несъответствие има и че кодът няма да доведе да посочения в книгата изход, който (изходът) се различава от заложения в Judge. И точно затова предлагам корекция на изхода, посочен в книгата, така че да съответства на изхода, очакван от Judge. Надявам се, че не приемате "Area = 1500.0" и "1500" за два еднакви изхода, в противен случай дискусията е излишна!

**Comment by vncpetrov** [comment]
Оправих изхода в книгата да съответства на дадения примерен код.
https://github.com/SoftUni/Programming-Basics-Book-Java-BG/commit/255dc4c2f2e102351c59a068a2547aeae867fba8

**Comment by AngelKalinkov** [comment]
Сега, ако махнете от изхода и String частите: "Area = " и "Perimeter = ", ще може да се каже, че сте го оправили :)
