### ISSUE TITLE
Глава 3.2. Задача: фирма - недостатъчно информация в условието и грешно решение

### ISSUE THREAD

**Issue by AngelKalinkov** [SoftUni/Programming-Basics-Book-Java-BG#24]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-Java-BG/blob/master/chapter-03-simple-conditions-exam-problems.md

## Описание
В условието се казва: "Фирма получава заявка за изработването на проект, за който са необходими определен брой часове. Фирмата разполага с определен брой дни. През 10% от дните служителите са на обучение и не могат да работят по проекта. Един нормален работен ден във фирмата е 8 часа. Всеки служител може да работи по проекта в извънработно време по 2 часа на ден."
Никъде не се посочва какъв е броят на служителите, от което можем да заключим, че той ще бъде въведен като вход на конзолата. Посоченият в задачата вход е следния:
"Входът се чете от конзолата и съдържа точно 3 реда:
    На първия ред са необходимите часове – цяло число в интервала [0 ... 200 000].
    На втория ред са дните, с които фирмата разполага – цяло число в интервала [0 ... 20 000].
    На третия ред е броят на служителите, работещи извънредно – цяло число в интервала [0 ... 200]."
По нататък в решението се казва: "Следващата стъпка е да изчислим количеството на работните часове като умножим работните дни по 8 (всеки ден се работи по 8 часа) и ги съберем с извънработното време. Работните дни са равни на 90% от дните, с които фирмата разполага. Извънработното време е равно на резултата от умножението на броя на работещите извънредно служители с 2 (възможните часове извънработно време), като това също се умножава по броя на работните дни."
Тоест общия брой отработени часове във фирмата намираме като съберем часовете за един служител (дните * 8) с овъртайма на работещите извънредно (дните * 2 * работниците)!!!??? Шах с пешката и мат...

## Текст след поправката
Вариант 1: Да се добави към входните данни общия брой служители и да се коригират решението и показания в задачата изход, както и съответно заложените вход и изход в Judge.
Вариант 2: Да се уточни в условието на задачата, че тези 8 часа са работното време на ден за всички служители. В такъв случай е добре цифрата 8 да бъде заменена с някое доста по-голямо число, за да не въвежда условието в заблуждение и да е по-реалистично.

**Comment by udarensamolet** [comment]
>> Никъде не се посочва какъв е броят на служителите, от което можем да заключим, че той ще бъде въведен като вход на конзолата. 

Посочено е, че трети ред от входните данни съдържа броя на служителите, които работят извънредно.  
>> На третия ред е броят на служителите, работещи извънредно – цяло число в интервала [0 ... 200].

Също така, в условието е отбелязано, че 
>> Всеки служител може да работи по проекта в извънработно време по 2 часа на ден.

От тук следва, че общият брой служители е и броят на работещите извънредно.

---

>> Тоест общия брой отработени часове във фирмата намираме като съберем часовете за един служител (дните * 8) с овъртайма на работещите извънредно (дните * 2 * работниците)

Не, в решението е обяснено подробно как се намират отработените часове.

**Comment by AngelKalinkov** [comment]
Моите уважения, но ако в условието пише: "Всеки служител може да работи по проекта в извънредно време по 2 часа на ден", то от това по никакъв начин не следва, че всички служители са работили извънредно. И ако общият брой на служителите е и броят на работещите извънредно, няма никакъв смисъл на входа да се подава броят на работилите извънредно, а не просто броят на служителите. Но това нямаше да е такъв проблем, ако задачата беше решена вярно. В решението наистина подробно е обяснено, че общия брой часове, изработени от всички служители се намира така: (дните * 8) + (дните * 2 * работниците). Ако, както твърдите, всички служители са работили извънредно, моля да ме убедите, че това решение е вярно!
