### ISSUE TITLE
Глава 3.2. Задача: реколта - некоректен символ в очаквания изход

### ISSUE THREAD

**Issue by AngelKalinkov** [SoftUni/Programming-Basics-Book-Java-BG#26]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-Java-BG/blob/master/chapter-03-simple-conditions-exam-problems.md
## Описание
- [x] В изхода, посочен в задачата присъства символът "→", докато в изхода, заложен в Judge са използвани символите "->".
- [x] Освен това като условие за входа на задачата е посочено следното:
"Входът се чете от конзолата и се състои от точно 4 реда:
    1-ви ред: X кв.м е лозето – цяло число в интервала [10...5000].
    2-ри ред: Y грозде за един кв.м. – реално число в интервала [0.00...10.00].
    3-ти ред: Z нужни литри вино – цяло число в интервала [1...600].
    4-ти ред: брой работници – цяло число в интервала [1...20]."
Тоест три цели и едно дробно число. В последващото решение обаче се декларират четири променливи от тип double.

## Текущ текст
https://github.com/SoftUni/Programming-Basics-Book-Java-BG/blob/master/assets/chapter-3-2-images/04.Harvest-01.png

**Comment by vncpetrov** [comment]
Оправихме ги.
