### ISSUE TITLE
Глава 3.2. Задача: тръби в басейн - противоречия в условието и разлика между изхода и заложения в Judge

### ISSUE THREAD

**Issue by AngelKalinkov** [SoftUni/Programming-Basics-Book-Java-BG#27]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-Java-BG/blob/master/chapter-03-simple-conditions-exam-problems.md
## Описание
- [x] В условието, за изходните данни се казва: "Всички проценти да се форматират до цяло число (без закръгляне)." А няколко реда по-надолу пише: "Имайте предвид, че поради закръглянето до цяло число се губят данни и e нормално сборът на процентите да е 99%, а не 100%." В решението на задачата пък се казва: "Стойностите ще бъдат вмъкнати с форматиращи низове и тъй като има условие резултата в проценти да се форматира до две цифри след десетичния знак без закръгляне, то за целта ще използваме метода Math.floor(...)." В крайна сметка не става ясно, процентите до цяло число или до две цифри след десетичната запетая трябва да се форматират и със закръгляне или без.
- [ ] Изходът, който се очаква в задачата е:
The pool is 66% full. Pipe 1: 45%. Pipe2: 54%. или For 2.5 hours the pool overflows with 400 liters.
Докато в Judge е заложен изход:
66
1
45
2
54
или
2,5
400
## Текст след поправката
Да се уточни, че процентите трябва да се закръглят надолу до цяло число. Да се уеднаквят изхода, показан в книгата, с този, който е заложен в Judge.

**Comment by vncpetrov** [comment]
Само по себе си няма как да направим форматиране до цяло число, без да го закръглим.

Уеднаквих нещата.
