### ISSUE TITLE
Грешен код за проверка за просто число в глава 7.2 (По-сложни цикли)

### ISSUE THREAD

**Issue by nakov** [SoftUni/Programming-Basics-Book-Java-BG#28]
## Линк към файла

https://github.com/SoftUni/Programming-Basics-Book-Java-BG/blob/master/assets/chapter-7-1-images/10.Prime-numbers-01.png

Този код е грешен. Да се поправи!

## Описание

В глава 7.2 в примера за оператор `break` за проверка за просто число има грешка:

https://github.com/SoftUni/Programming-Basics-Book-Java-BG/blob/master/chapter-07-complex-loops.md#Пример-проверка-за-просто-число-Оператор-break

Да се синхронизира текста ореди кода и самият код, защото не си съотвестват. Кодът е сбъркан.

## Текущ текст

```boolean prime = n < 2;```

## Текст след поправката

```boolean prime = n >= 2;```

Да изчезне и проверката:

```if (n<2) ...```

**Comment by udarensamolet** [comment]
Fixed with [d5a5360](https://github.com/SoftUni/Programming-Basics-Book-Java-BG/commit/d5a5360ef393bb68ea5e9f85ab37f33c497599c9).
