### ISSUE TITLE
Грешна картинка и обяснения за try-catch

### ISSUE THREAD

**Issue by nakov** [SoftUni/Programming-Basics-Book-Java-BG#29]
## Линк към файла

https://github.com/SoftUni/Programming-Basics-Book-Java-BG/blob/master/assets/chapter-7-1-images/00.Try-catch-01.png

## Описание

Вж. глава 7, секцията за `try-catch`: https://github.com/SoftUni/Programming-Basics-Book-Java-BG/blob/master/chapter-07-complex-loops.md#Конструкция-на-try-catch

В Java няма `try-catch` конструкция (хвани каквото и да е). Трябва изрично да се зададе име на клас или базов клас за грешката, например:

```java
try {
  ...
} catch (Exception ex) {
  ...
}
```

При копирането от C# не е съобразено, че конструкцията е леко по-смотана в Java и не може да не се зададе има на клас (няма _catch all_ синтаксис).

## Задачи (как да поправим проблема?)

- Да се преработи картинката, за да е вярна.
- Да се огледа текста дали описва правилно картинката. Да се обясни, че се слага `catch (Exception ex)` и че това хваща всякакви грешки в променлива с име `ex`.
- Да се преправи картинката в примерната задачата да се хващат всички изключения, щото иначе трябва да се обяснява защо се хваща `NumberFormatException` (а няма нужда от такива подробности).

**Comment by vncpetrov** [comment]
За преглед.

**Comment by nakov** [comment]
Така е добре.
