### ISSUE TITLE
Глава 3.2. Задача: тръби в басейн - разминаване на изхода в задачата с този от Judje

### ISSUE THREAD

**Issue by AngelKalinkov** [SoftUni/Programming-Basics-Book-Java-BG#30]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-Java-BG/blob/master/chapter-03-simple-conditions-exam-problems.md
## Описание
В тази задача оправихте противоречията в условието относно закръглянето на процентите, но оставихте нерешен проблема с изхода. Изходът, който се очаква в задачата е:
The pool is 66% full. Pipe 1: 45%. Pipe2: 54%. или For 2.5 hours the pool overflows with 400 liters.
Докато в Judge е заложен изход:
66
1
45
2
54
или
2,5
400
Тоест само числови стойности, без текст. Или поправете изхода в книгата и съответно кода, който сте написали, за да се стигне до него, или заложете нов изход в Judge, който да съответства на този в книгата.

**Comment by vncpetrov** [comment]
Checks if the numbers in the user output match the expected output. Intelligently skips the unneeded messages in the user output like "Please enter a number n: ". Works for integer and floating-point numbers. Compares with precision of 2 digits after the decimal point. If the expected output is text like "error", compares the texts intelligently (lowercase, skipping whitespace and punctuation).

Това е стратегия на Judge.  На доста задачи е такава стратегията. Не виждам проблем.

**Comment by AngelKalinkov** [comment]
Разбрах и благодаря за уточнението! Недоразумението дойде от това, че тук https://judge.softuni.bg/Contests/Practice/Index/652#1 и тук https://judge.softuni.bg/Contests/Practice/Index/179#1 задачата е с малко различие в условието и затова с един и същ код не минава 100/100 и на двете места.
