### ISSUE TITLE
Глава 3.2. Задача: фирма - грешно решение

### ISSUE THREAD

**Issue by AngelKalinkov** [SoftUni/Programming-Basics-Book-Java-BG#32]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-Java-BG/blob/master/chapter-03-simple-conditions-exam-problems.md
## Описание
Колеги, извинявам се, ако ставам досаден, но това, че променихте изчисляването на извънредните часове означава, че работниците са работили 2 часа допълнително дори и през тези 10% от времето, когато те са били на обучение, а според условието на задачата тогава те не могат да работят по проекта. Сами разбирате, че това не е правилно. В момента решението, което сте замъглили е:
> double workDays = availableDays * 0.9;
double overtime = workers * 2 * availableDays;
double workHours = Math.floor(workDays * 8 + overtime);

А това е решението, което Ви предлагам:
> double workDays = availableDays * 0.9;
double overtime = workers * 2 * workDays;
double workHours = Math.floor(workers * 8 * workDays + overtime);

Ако го приемете за вярно, би трябвало да промените и очакваните изходни данни, както и заложения изход в Judge.

**Comment by udarensamolet** [comment]
Fixed.
