### ISSUE TITLE
Глава 4.1. Пример: вид животно - непълен код

### ISSUE THREAD

**Issue by AngelKalinkov** [SoftUni/Programming-Basics-Book-Java-BG#33]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-Java-BG/blob/master/chapter-04-complex-conditions.md
## Описание
Липсва break оператор след конструкцията на последния case етикет.
## Текущ текст
https://github.com/SoftUni/Programming-Basics-Book-Java-BG/blob/master/assets/chapter-4-1-images/10.Animal-type-01.png
## Текст след поправката
![capture1](https://user-images.githubusercontent.com/31779913/30929620-a791aed2-a3c7-11e7-83e8-ab79af29e210.JPG)

**Comment by vncpetrov** [comment]
https://github.com/SoftUni/Programming-Basics-Book-Java-BG/commit/d24b17563c02753d90b095738360845558b28119
