### ISSUE TITLE
Грешен изход в условие на задача.

### ISSUE THREAD

**Issue by Tuscann** [SoftUni/Programming-Basics-Book-Java-BG#34]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-Java-BG/blob/master/chapter-08-exam-preparation.md
## Описание
Задача: Поредица от нарастващи елементи

Вход        |  Изход
 4 5 6 7 8 |  **2**

Изхода трябва да бъде **4**

В Judge показва правилно отоговора 4.

**Comment by vncpetrov** [comment]
Fixed.
https://github.com/SoftUni/Programming-Basics-Book-Java-BG/commit/8610fa0f47d88ef966f15d757298cb595df48f1c
