### ISSUE TITLE
Глава 4.2. Задача: пътешествие - некоректен код

### ISSUE THREAD

**Issue by AngelKalinkov** [SoftUni/Programming-Basics-Book-Java-BG#35]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-Java-BG/blob/master/chapter-04-complex-conditions-exam-problems.md
## Описание
- [x] В конструкцията на основната проверка, с която се проверява бюджета, **else if** и **else** се повтарят по два пъти.
- [x] Вложената проверка, с която се проверява сезона, е направена само за единия сезон. Това означава, че ако при въвеждането му в конзолата допуснем правописна грешка, на изхода вместо празен ред ще получим данните за другия сезон.
- [x] Защо се използва **formatter.format(moneySpend)**, след като никъде преди това не е импортиран **DecimalFormat**? Няма ли да е по-удачно да използваме **moneySpend.setScale(2, RoundingMode.HALF_UP)**?

**Comment by Antoveravip** [comment]
1. В конструкцията на основната проверка, с която се проверява бюджета, else if и else се повтарят по два пъти.
Коментар: не се повтарят 2 пъти, а са 2 различни картинки и краят на едната е прекъсната преди следващият и обратното.

2. Вложената проверка, с която се проверява сезона, е направена само за единия сезон. Това означава, че ако при въвеждането му в конзолата допуснем правописна грешка, на изхода вместо празен ред ще получим данните за другия сезон.
Коментар: Считам въпросната точка за ненужно вдигане на забележка! Доколкото съм запознат, в условието на всички задачи се разчита на коректно подаден вход. Ако разгледаш всички останали - никъде не се правят изрични проверки за коректността на въведените данни. 
Въпросната проверка е направена така с цел - да се покаже, че е възможно да се приеме за даденост едната стойност и при нужда само да се замени.
Дори да ми се наложи да проверявам входните данни, това ще бъде направено в много по начален етап и ще върна съобщение за некоректен вход, така че достигайки до тази част на кода - няма да има никакви проблеми.

3. Защо се използва formatter.format(moneySpend), след като никъде преди това не е импортиран DecimalFormat? Няма ли да е по-удачно да използваме moneySpend.setScale(2, RoundingMode.HALF_UP)?
Коментар: Защо реши, че не е импортиран? Разглеждал ли си кодът за задачата в репозиторито?
Идеята е да не се показва целият код в книгата, за да се замисли пишещият, кое не е наред, да седне да прочете и да си въведе липсващият код.
На този етап от книгата вече всеки сериозно четящ и практикуващ ще се е запознал с различните видове форматери и начини на форматиране на изходните данни.
Относно кое е по-удачно - въпрос на решение в момента. Винаги всеки един код може да се напише "по-удачно" поне по минимум 4 различни начина.

П.С. Няма да затварям така изброените от теб проблеми. Ще ги оставя на екипът да реши до колко са удачни.

**Comment by AngelKalinkov** [comment]
1. Три картинки, наредени плътно една след друга, без текст между тях, изглеждат като една. Ако книгата излезе на хартиен носител, това че картинките са три като забележка под текста ли ще бъде уточнено?

2. Ако искам да закупя самолетен билет до Австрия, ще се почувствам доста неприятно, заради грешен правопис да заплатя стойността на билета до Австралия.

3. Приемам забележката Ви. Ако наистина целта е била пишещият да се замисли кое не е наред, постигнали сте го.

**Comment by Antoveravip** [comment]
1. Така написано вече има смисъл. Приема се градивният елемент. Оправени са разстоянията между снимките.

2. Няма какво да ти кажа повече по тази точка, щом не си хванал замисъла на написаното в текста и смисъла на предният ми коментар.

3. Дори и тук ще приема забележката и ще добавя изрично какъв е форматера, за да по ясно. Вече и това е направено.

**Comment by AngelKalinkov** [comment]
2. 
> Въпросната проверка е направена така с цел - да се покаже, че е възможно да се приеме за даденост едната стойност и при нужда само да се замени.

Тази част от обяснението ме кара да се съглася и да приема доводите Ви. Благодаря за градивния диалог. 👍
