### ISSUE TITLE
Глава 8.1, задача "Генериране на правоъгълници"

### ISSUE THREAD

**Issue by nakov** [SoftUni/Programming-Basics-Book-Java-BG#36]
## Линк към файла

https://github.com/SoftUni/Programming-Basics-Book-Java-BG/blob/master/chapter-08-exam-preparation.md#Задача-генериране-на-правоъгълници

## Описание

Променливата е `volume`, а съдържа **лице на правоъгълник**. Трябва да се казва `area`.

Има няколко картинки със сорс код, които трябва да се поправят, например тази:

https://github.com/SoftUni/Programming-Basics-Book-Java-BG/blob/master/assets/chapter-8-1-images/12.Generating-rectangles-01.png

**Comment by vncpetrov** [comment]
Fixed.
