### ISSUE TITLE
Blur на изображения

### ISSUE THREAD

**Issue by Antoveravip** [SoftUni/Programming-Basics-Book-Java-BG#4]
До каква степен на blur е желателен за изображение? Понеже конкретното изображение ми се струва, че при форматът на книгата на хартия, дори при текущите технологии на печат, ще излезне едно голямо петно.

Въпросът ми е трябва ли да го коригирам с по-лек blur?

## Линк към файла
https://java-book.softuni.bg/chapter-02-simple-calculations-exam-problems.html#simple-calculations
## Описание
Например става дума за изображението след текста: тъй като той работи с променливи от тип double, за броя редици и колони създаваме променливи също от този тип.

## Текущ текст
https://java-book.softuni.bg/assets/chapter-2-2-images/01.Training-lab-04.png

**Comment by udarensamolet** [comment]
За blur-ване използваме степен 6 или 7. В C# книгата ги правихме по този начин.

**Comment by nakov** [comment]
Ами сега добре е направено според мен.

Единствената ми забележка е, че по ръбовете сега има рязко отрязване:
![image](https://user-images.githubusercontent.com/1689586/28247249-a6171874-6a35-11e7-94eb-b969c75709c0.png)
Този дефект ще трябва да го оправяме повсеместно: увеличава се image canvas size и по ръбовете се прави повторен blur:
![image](https://user-images.githubusercontent.com/1689586/28247270-e9eeb64c-6a35-11e7-9d8c-a5d77b8e317a.png)

**Comment by udarensamolet** [comment]
done
