### ISSUE TITLE
Глава 4.2. Задача: хотелска стая - липсващи точки на изхода

### ISSUE THREAD

**Issue by AngelKalinkov** [SoftUni/Programming-Basics-Book-Java-BG#40]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-Java-BG/blob/master/chapter-04-complex-conditions-exam-problems.md
## Описание
В условието, там където се описва изхода, липсват точките накрая. Липсва също така и на примерните вход и изход, при вход "June", на втория ред на изхода.

**Comment by Antoveravip** [comment]
Благодаря за забележката. Оправено е.
