### ISSUE TITLE
Глава 5.1. Пример: сумиране на числа - грешно решение

### ISSUE THREAD

**Issue by AngelKalinkov** [SoftUni/Programming-Basics-Book-Java-BG#41]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-Java-BG/blob/master/chapter-05-loops.md
## Описание
Решението, посочено в тази задача, всъщност е решението на следващата - Пример: най-голямо число.
## Текущ текст
https://github.com/SoftUni/Programming-Basics-Book-Java-BG/blob/master/assets/chapter-5-1-images/04.Sum-numbers-01.png
## Текст след поправката
![capture1](https://user-images.githubusercontent.com/31779913/31146654-027b812a-a890-11e7-9a69-3b1e4bda09bc.JPG)

**Comment by vncpetrov** [comment]
Fixed.
https://github.com/SoftUni/Programming-Basics-Book-Java-BG/commit/7e9dd19364b5b6a04b224f864f6301885a2d411b
