### ISSUE TITLE
Глава 5.1. Задача: четни / нечетни позиции - грешен изход

### ISSUE THREAD

**Issue by AngelKalinkov** [SoftUni/Programming-Basics-Book-Java-BG#43]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-Java-BG/blob/master/chapter-05-loops.md
## Описание
При вход:
2
1.5
-2.5
посоченият изход е невъзможен.
## Текущ текст
![screenshot-2017-10-8 softuni programming-basics-book-java-bg](https://user-images.githubusercontent.com/31779913/31312415-3ab532e6-abcb-11e7-894d-8cf936ca77c6.png)

## Текст след поправката
![capture1](https://user-images.githubusercontent.com/31779913/31312399-b42f982e-abca-11e7-99f9-1183966b8c24.JPG)

**Comment by vncpetrov** [comment]
Fixed.
