### ISSUE TITLE
Глава 6.1. Пример: правоъгълник от N x N звездички - грешка в кода

### ISSUE THREAD

**Issue by AngelKalinkov** [SoftUni/Programming-Basics-Book-Java-BG#44]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-Java-BG/blob/master/chapter-06-nested-loops.md
## Описание
В конструкцията на вътрешния за метода цикъл, крайната стойност е грешна. Вероятно е останала при копирането на решението от предната задача.
## Текущ текст
https://github.com/SoftUni/Programming-Basics-Book-Java-BG/blob/master/assets/chapter-6-1-images/02.Rectangle-of-N-x-N-stars-01.png
## Текст след поправката
for (int i = 0; i < numberOfStars; i++)

**Comment by udarensamolet** [comment]
Fixed with [6927608](https://github.com/SoftUni/Programming-Basics-Book-Java-BG/commit/69276080d6e997e43f87b82ea004d49168a9f029).
