### ISSUE TITLE
Глава 6.1. Пример: триъгълник от долари - грешен код

### ISSUE THREAD

**Issue by AngelKalinkov** [SoftUni/Programming-Basics-Book-Java-BG#45]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-Java-BG/blob/master/chapter-06-nested-loops.md
## Описание
С посочения код не може да се отпечата желания триъгълник от долари.
## Текущ текст
https://github.com/SoftUni/Programming-Basics-Book-Java-BG/blob/master/assets/chapter-6-1-images/04.Triangle-of-dollars-01.png
## Текст след поправката
![capture1](https://user-images.githubusercontent.com/31779913/31578404-46127fa0-b129-11e7-9ee4-b7a43d6dfdd6.JPG)

**Comment by udarensamolet** [comment]
Fixed with [a52f6a0](https://github.com/SoftUni/Programming-Basics-Book-Java-BG/commit/a52f6a08d4bbb8f299f581175634b9f621a71d32).
