### ISSUE TITLE
Глава 6.1. Пример: ромб от звездички - грешка в кода

### ISSUE THREAD

**Issue by AngelKalinkov** [SoftUni/Programming-Basics-Book-Java-BG#46]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-Java-BG/blob/master/chapter-06-nested-loops.md
## Описание
В тялото на втория вложен цикъл, преди звездичката трябва да има интервал.
## Текущ текст
https://github.com/SoftUni/Programming-Basics-Book-Java-BG/blob/master/assets/chapter-6-1-images/06.Rhombus-of-stars-01.png

**Comment by udarensamolet** [comment]
Fixed with [1165a38](https://github.com/SoftUni/Programming-Basics-Book-Java-BG/commit/1165a38d78e07be18560778c57e6344fbd0c2da8).
