### ISSUE TITLE
Глава 6.1. Пример: слънчеви очила - грешка в кода

### ISSUE THREAD

**Issue by AngelKalinkov** [SoftUni/Programming-Basics-Book-Java-BG#47]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-Java-BG/blob/master/chapter-06-nested-loops.md
## Описание
При отпечатването на горната и долната част, третите редове трябв да са println. Също на втория ред за отпечатването на долната част звездичката трябва да се замени с интервал, така както е в горната част.
## Текущ текст
https://github.com/SoftUni/Programming-Basics-Book-Java-BG/blob/master/assets/chapter-6-1-images/08.Sunglasses-01.png

**Comment by udarensamolet** [comment]
Fixed with [114007f](https://github.com/SoftUni/Programming-Basics-Book-Java-BG/commit/114007f545ce4c408bbddae81533a3784240d68b).
