### ISSUE TITLE
Глава 6.1. Пример: диамант - неточности в условието

### ISSUE THREAD

**Issue by AngelKalinkov** [SoftUni/Programming-Basics-Book-Java-BG#48]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-Java-BG/blob/master/chapter-06-nested-loops.md
## Описание
В условието се казва, че трябва да се напише програма, която да отпечатва "диамант с размери n x n". Това обаче не е коректно, тъй като от посочените примери за вход и изход се вижда, че когато n е положително число, изходната фигура е с размери n x n-1.
Също така в условието се казва, че ако n е четно, горната част започва с една звезда, а ако е нечетно с две. Всъщност обаче е точно обратното.

**Comment by udarensamolet** [comment]
Fixed with [f99c17f](https://github.com/SoftUni/Programming-Basics-Book-Java-BG/commit/f99c17f2c6f32b0ca9c1d69aab69c215a9bb7031) and [162e4d4](https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/commit/162e4d47d34f6530799abe635b7dea5667b21429#diff-d8068aa432e10c54e2b69cd596714c1a).
