### ISSUE TITLE
Глава 5.2. Задача: хистограма - грешка в изхода

### ISSUE THREAD

**Issue by AngelKalinkov** [SoftUni/Programming-Basics-Book-Java-BG#49]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-Java-BG/blob/master/chapter-05-loops-exam-problems.md
## Описание
На последния пример за вход и изход има грешка в изхода.
## Текущ текст
57.14%
7.14%
7.14%
14.29%
14.29%
## Текст след поправката
57.14%
14.29%
7.14%
14.29%
7.14%

**Comment by udarensamolet** [comment]
Fixed with [2d77f04](https://github.com/SoftUni/Programming-Basics-Book-Java-BG/commit/2d77f0434328b10dadbd0b724ed6212a0c1a3dd4).
