### ISSUE TITLE
Глава 10. Методи -> няма нужда методите в Java да са public

### ISSUE THREAD

**Issue by nakov** [SoftUni/Programming-Basics-Book-Java-BG#50]
## Линк към файла

https://github.com/SoftUni/Programming-Basics-Book-Java-BG/blob/master/chapter-10-methods.md

## Описание

Всички примерни методи "**Глава 10. Методи**" в Java книгата са декларирани като `public`. Това не е необходимо и не е добра практика като цяло. Да се изтрие `public` декларацията, както и обясненията около нея. Трябва да се редактират доста картинки, както и да се огледа текста.

**Comment by vncpetrov** [comment]
Оправил съм картинките, както и обясненията около публичната декларация. Единствено за модификатори се споменава в следния абзац:
![image](https://user-images.githubusercontent.com/20843160/32235850-410c7f5e-be69-11e7-85f3-9b723913155c.png)
Да го махам или да го оставя?

**Comment by nakov** [comment]
Или да се махне, или да се преправи, за да е вярно спрямо дадения пример
(където няма модификатор за видимост).

Regards,

Svetlin Nakov

Software University – https://softuni.bg


2017-10-31 18:28 GMT+02:00 vncpetrov <notifications@github.com>:

**Comment by nakov** [comment]
Или да се махне, или да се преправи, за да е вярно спрямо дадения пример (където няма модификатор за видимост).

**Comment by nakov** [comment]
Всичко е оправено по този казус.
