### ISSUE TITLE
Объркана задача: "Известия" в глава "10. Методи"

### ISSUE THREAD

**Issue by nakov** [SoftUni/Programming-Basics-Book-Java-BG#51]
## Линк към файла

https://github.com/SoftUni/Programming-Basics-Book-Java-BG/blob/master/chapter-10-methods.md#Задача-известия

## Описание

**Описанието на задачата "Известия" е доста объркано** и не съответства а примерния вход и изход. Аз лично няколко пъти го четох и не го разбрах, примерите не можах да ги разгадая и като цяло ми се стори странно изискваното поведение.

## Коментари

Предлагам няколко промени:
 - От входа да се четет `n` съобщения. Всяко съобщения започва с `messageType`: `success`, `warning` или `error`.
 - При `success` да се четат `operation` + `message`.
 - При `warning` да се чете само `message`.
 - При `error` да се чете `operation` + `message` + `errorCode`.
 - В изхода да се сложи по един празен ред след всяка команда.
 - В изхода след заглавния ред за всяка съобщение да се отпечатат толкова силвола `=`, колкото е дълъг съответният заглавен ред (вж. примерния изход).

Примерен вход:
```
4
error
credit card purchase
Invalid customer address
500
warning
Email not confirmed
success
user registration
User registered successfully
warning
Customer has not email assigned
```

Примерен изход:
```
Error: Failed to execute credit card purchase.
==============================================
Reason: Invalid customer address.
Error code: 500.

Warning: Email not confirmed.
=============================

Successfully executed user registration.
========================================
User registered successfully.

Warning: Customer has not email assigned.
=========================================

```

Съответно трябва да се напишат няколко метода:

```java
static void showSuccessMessage(String operation, String message) { ... }

static void showWarningMessage(String message) { ... }

static void showErrorMessage(String operation, String message, int errorCode) { ... }

static void readAndProcessMessage() {
    Scanner scanner = new Scanner(System.in);
    String messageType = scanner.nextLine();
    switch (messageType) {
        // TODO: check for "success", "warning" and "error"
    }
}
```

Накрая главният метод ще вика останалите методи:

```java
public static void main(String[] args) throws Exception {
    Scanner scanner = new Scanner(System.in);
    int n = scanner.nextInt();
    for (int i = 0; i < n; i++)
        readAndProcessMessage();
}
```

Да се направят и нови тестове в Judge: https://judge.softuni.bg/Contests/Practice/Index/665#12

**Comment by vncpetrov** [comment]
Fixed. 
Това е решението: https://pastebin.com/WTFhu5Aa

**Comment by nakov** [comment]
Оправено.
