### ISSUE TITLE
Глава 6.2. Задача: пеперуда - грешка в описанието на решението

### ISSUE THREAD

**Issue by AngelKalinkov** [SoftUni/Programming-Basics-Book-Java-BG#52]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-Java-BG/blob/master/chapter-06-nested-loops-exam-problems.md
## Описание
В описанието на решението се казва:
> От примерите можем да забележим, че на четен ред имаме начало *, среда \ / и край *, а на нечетен - начало -, среда \ / и край -.

Всъщност е точно обратно.

**Comment by vncpetrov** [comment]
Fixed

https://github.com/SoftUni/Programming-Basics-Book-Java-BG/commit/d91c6ddf3f55d918f87c821cb7fe5ca52cb964a5
