### ISSUE TITLE
Глава 6.2. Задача: знак "Стоп" - неточност в обяснението на решението

### ISSUE THREAD

**Issue by AngelKalinkov** [SoftUni/Programming-Basics-Book-Java-BG#53]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-Java-BG/blob/master/chapter-06-nested-loops-exam-problems.md
## Описание
В обяснението на решението се казва:
> За да можем да използваме отново създадените променливи, трябва да намалим dots с 1 и underscopes с 2, защото ние вече сме отпечатали първия ред, а точките и долните черти в горната част от фигурата на всеки ред намаляват.

Това е грешно твърдение, тъй като **underscopes** (тук има правописна грешка) намаляват само във втория ред, а в следващите се увеличават. Затова в цитирания израз ще е по-правилно да се каже: "..., а точките и долните черти в следващия ред намаляват."

**Comment by vncpetrov** [comment]
Fixed. https://github.com/SoftUni/Programming-Basics-Book-Java-BG/commit/106acf884e5b15d6153a26c63a596685d687634c
