### ISSUE TITLE
Глава 7.1. Пример: проверка за просто число - грешка в кода на решението

### ISSUE THREAD

**Issue by AngelKalinkov** [SoftUni/Programming-Basics-Book-Java-BG#54]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-Java-BG/blob/master/chapter-07-complex-loops.md
## Описание
- [x] В тялото на цикъла има проверка, чието условие е сгрешено. Трябва да бъде (n % i == 0).

- [x] Освен това накрая в описанието на решението се казва:
> Оставаме да добавите проверка дали входното число е по-голямо от 1, защото по дефиниция числа като 0, 1, -1 и -2 не са прости.

Защо трябва да правим тази проверка, след като, за да отпечаме на конзолата "Prime", проверяваме дали е верен булевия израз (n >= 2)?
## Текущ текст
https://github.com/SoftUni/Programming-Basics-Book-Java-BG/blob/master/assets/chapter-7-1-images/10.Prime-numbers-01.png

**Comment by vncpetrov** [comment]
Fixed.
