### ISSUE TITLE
Глава 7.1. - грешка в описанието на наученото 

### ISSUE THREAD

**Issue by AngelKalinkov** [SoftUni/Programming-Basics-Book-Java-BG#55]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-Java-BG/blob/master/chapter-07-complex-loops.md
## Описание
В секцията "Какво научихме в тази глава?", в кода, описващ try-catch, липсва параметъра на catch и къдравата скоба преди тялото.

**Comment by vncpetrov** [comment]
Fixed.
