### ISSUE TITLE
Глава 7.2. Задача: генератор на тъпи пароли - неточност в кода

### ISSUE THREAD

**Issue by AngelKalinkov** [SoftUni/Programming-Basics-Book-Java-BG#56]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-Java-BG/blob/master/chapter-07-complex-loops-exam-problems.md
## Описание
В цикъла за втория буквен символ в паролата, променливата е декларирана като int, а не както при първия като char, а в реда за печат плейсхолдърите не отговарят на типа на променливите. Програмата сработва и така, но все пак...
## Текущ текст
https://github.com/SoftUni/Programming-Basics-Book-Java-BG/blob/master/assets/chapter-7-2-images/01.Stupid-password-generator-02.png

**Comment by vncpetrov** [comment]
Fixed.
