### ISSUE TITLE
Глава 7.2. Задача: спиращо число - неточност в примерния вход и изход

### ISSUE THREAD

**Issue by AngelKalinkov** [SoftUni/Programming-Basics-Book-Java-BG#57]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-Java-BG/blob/master/chapter-07-complex-loops-exam-problems.md
## Описание
В третия пример за вход и изход част от входа е записана в колонката за изход, а изхода в колонката за обяснения.

**Comment by vncpetrov** [comment]
Fixed.
