### ISSUE TITLE
Глава 8.1. Задача: поредица от нарастващи елементи - ненужно повторение в примерния вход-изход

### ISSUE THREAD

**Issue by AngelKalinkov** [SoftUni/Programming-Basics-Book-Java-BG#58]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-Java-BG/blob/master/chapter-08-exam-preparation.md
## Описание
В примерния вход и изход, третия и четвъртия пример се повтарят като пети и шести, като на шестия дори е объркан изхода.

**Comment by vncpetrov** [comment]
Fixed.
