### ISSUE TITLE
Глава 8.1. Задача: генериране на правоъгълници - неточност в решението

### ISSUE THREAD

**Issue by AngelKalinkov** [SoftUni/Programming-Basics-Book-Java-BG#59]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-Java-BG/blob/master/chapter-08-exam-preparation.md
## Описание
В описанието на решението се казва: 
> Тъй като координатите може да са отрицателни, ще ползваме абсолютни стойности.

Използването на Math.abs е ненужно, защото когато от отрицателно число вадим по-малко отрицателно число се получава положително число. Дори и правоъгълникът да е с отрицателни координати, е невъзможно някоя от страните му да е с отрицателна дължина (освен, ако не е някъде в антиматерията :) .

**Comment by nakov** [comment]
Напълно си прав: няма нужда от абсолютна стойност, освен ако не са разменени 'left' и 'right' (по условие не може да са разменени). Ще нанеса корекции навсякъде: в петте книги (C#, Java, JS, Python и C++).
