### ISSUE TITLE
Глава 9.1. Задача: пет специални букви - грешка в кода, посочен в Насоки и подсказки

### ISSUE THREAD

**Issue by AngelKalinkov** [SoftUni/Programming-Basics-Book-Java-BG#60]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-Java-BG/blob/master/chapter-09-problems-for-champions.md
## Описание
В описанието на решението се казва: 
> За начало ще добавим първата буква към началния стринг.
![image](https://user-images.githubusercontent.com/31779913/34017969-a1d42258-e130-11e7-893a-fd63afdd5682.png)
След това ще обиколим останалите 4 с цикъл, проверявайки всеки път дали ги има със следното условие и метода indexOf(…).
![image](https://user-images.githubusercontent.com/31779913/34018036-ed501e8a-e130-11e7-88ff-a3420e41187c.png)

Променливата **l** на цикъла е обвързана с индексите на символите в стринга **current,** което означава, че максималната стойност, която тя трябва да приеме е **4.** По-нататък обаче, за установяване на теглото на символите от стринга **unique** се използва следния код: 
> 
![image](https://user-images.githubusercontent.com/31779913/34019092-e2ec1246-e135-11e7-9572-d17b085c654a.png)

Тук виждаме, че променливата **l** е обвързана с индексите на стринга **unique**. Следователно, ако стринга **current** има стойност **"aaaab"**, символът **'b'** ще има индекс **4** и ще бъде добавен към стринга **unique**, когато **l = 4**. В **unique**, обаче индексът на **'b'** ще бъде **1**. Което означава, че посоченият **switch** няма да проработи, защото излиза извън обхват и компилацията на кода ще бъде прекъсната от грешка.

За пресмятането на теглото на стринга **unique** е посочен кода: 
> 
![image](https://user-images.githubusercontent.com/31779913/34020107-091d88aa-e13b-11e7-8c70-88ca6e3f779b.png)

Той ще доведе до грешна стойност на **sum**, защото отново е обвързан с **l**. При **current = "aaaab"**, към 1*(теглото на 'a') няма да добавим 2*(теглото на 'b'), а 4*(теглото на 'b').

**Comment by nakov** [comment]
fixed
