### ISSUE TITLE
Глава 10. Задача: по-малко число - код на C#

### ISSUE THREAD

**Issue by AngelKalinkov** [SoftUni/Programming-Basics-Book-Java-BG#61]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-Java-BG/blob/master/chapter-10-methods.md
## Описание
Кодът явно е останал некоригиран от книгата на C#.
## Текущ текст
var min = getMin(getMin(num1, num2), num3);
## Текст след поправката
int min = getMin(getMin(num1, num2), num3);

**Comment by vncpetrov** [comment]
Fixed.
