### ISSUE TITLE
Глава 11. Техники за дебъгване на кода - техническа грешка

### ISSUE THREAD

**Issue by AngelKalinkov** [SoftUni/Programming-Basics-Book-Java-BG#62]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-Java-BG/blob/master/chapter-11-tricks-and-hacks.md
## Описание
В текста се казва
> Ще сложим стопер (breakpoint) на функцията System.out.println(…). За целта трябва да преместим курсора на реда, който печата на конзолата, и да натиснем [Ctrl + F8] или да кликнем с десния бутон на мишката от дясно на номера на реда.

Всъщност не съм сигурен как е в по-старите версии на IntelliJ IDEA, но във версия 2017.3.2 трябва да се кликне с левия бутон.

**Comment by vncpetrov** [comment]
Fixed.
