### ISSUE TITLE
Липсваща картинка

### ISSUE THREAD

**Issue by nakov** [SoftUni/Programming-Basics-Book-Java-BG#8]
![image](https://user-images.githubusercontent.com/1689586/29515036-5cc851ec-8673-11e7-97a7-867b91486990.png)

**Comment by vncpetrov** [comment]
Fixed. [https://github.com/SoftUni/Programming-Basics-Book-Java-BG/commit/b3b2e53b0907e529b465f609e475b1376863c808](https://github.com/SoftUni/Programming-Basics-Book-Java-BG/commit/b3b2e53b0907e529b465f609e475b1376863c808)
