### ISSUE TITLE
Приблизително еднакъв размер на шрифта: код, текст, картинки

### ISSUE THREAD

**Issue by nakov** [SoftUni/Programming-Basics-Book-Java-BG#9]
![image](https://user-images.githubusercontent.com/1689586/29515206-2912b332-8674-11e7-8f51-9643b1c8bac4.png)

**Comment by vncpetrov** [comment]
Fixed. [https://github.com/SoftUni/Programming-Basics-Book-Java-BG/commit/bf3cf56f909df15d15a3c60b3ad07c7b9437012f](https://github.com/SoftUni/Programming-Basics-Book-Java-BG/commit/bf3cf56f909df15d15a3c60b3ad07c7b9437012f)
